/**
 * Copyright (c) 2023. Cellpoint Digital
 * www.cellpointdigital.com
 *
 */
import org.apache.tools.ant.filters.ReplaceTokens

import java.time.*
import java.time.format.DateTimeFormatter
import java.util.regex.*

abstract class UseJavaFeaturesExtension {

    @Inject
    abstract Project getCurrentProject()

    JavaVersion javaVersion = JavaVersion.current()
    boolean processJavaResources = true
    boolean repositories = true;
    boolean dependencies = true;
    boolean test = true;
    boolean spotbugs = false;
    boolean jacoco = true;

    private final now = OffsetDateTime.now(ZoneOffset.UTC)
    private String semver

    private void applyIfExists(boolean enabled, String name) {
        if (enabled) {
            File overriding = currentProject.file("gradle/${name}.gradle")
            if (overriding.exists()) {
                currentProject.apply([from: overriding])
            } else {
                // search the file in root dir
                final String rootDir = currentProject.getRootDir()
                final File overridingRoot = currentProject.file("${rootDir}/gradle/${name}.gradle")
                if (currentProject != currentProject.rootProject && overridingRoot.exists()) {
                    currentProject.apply([from: overridingRoot])
                } else {
                    File addon = currentProject.file("${rootDir}/addons/src/${name}.gradle")
                    if (addon.exists()) {
                        currentProject.apply([from: addon])
                    }
                }
            }
        }
    }

    void configure() {

        if (!currentProject.plugins.hasPlugin('java')) {
            throw new GradleException("useJavaFeatures() can be used in project with 'java' plugin connected.")
        }

        applyIfExists(repositories, 'repositories')
        applyIfExists(dependencies, 'dependencies')
        applyIfExists(test, 'test')
        applyIfExists(spotbugs, 'spotbugs')
        applyIfExists(jacoco, 'jacoco')

        currentProject.compileJava.options.encoding = "UTF-8"
        currentProject.compileTestJava.options.encoding = "UTF-8"
        currentProject.java {
            sourceCompatibility = javaVersion
            targetCompatibility = javaVersion
        }

        if (currentProject.plugins.hasPlugin('org.springframework.boot')) {
            // apply dependencies from 'annotationProcessor' configuration
            currentProject.configurations {
                compileOnly {
                    extendsFrom annotationProcessor
                }
            }

            currentProject.bootJar {
                archiveFileName = 'server.jar'
            }
        }

        def gitDetails = currentProject.getParent().ext.gitDetails

        // calculate effective build version
        String runNumber = ext.has('runNumber') ? ext.get('runNumber') : System.getenv('GITHUB_RUN_NUMBER')

        String branchName
        if (ext.has('branchName')) { // from -PbranchName=xxxx parameter
            branchName = ext.branchName
        } else {
            if (System.getenv('GITHUB_EVENT_NAME') == 'release') {
                branchName = 'release/' + System.getenv('GITHUB_REF_NAME')
            } else {
                branchName = gitDetails.branchName
            }
        }

        if (branchName != null) {
            // checking GIT branch name
            def eq = ["dev", "main", "HEAD"]
            def start = ["feature/", "hotfix/", "bugfix/", "release/", "PR-"]
            def end = ["/merge"]
            if (!eq.contains(branchName)
                    && (start.find { branchName.startsWith(it) }) == null
                    && (end.find { branchName.endsWith(it) }) == null)
            {
                throw new GradleException("Unsupported branch name '" + branchName +
                        "', only ["+(eq+start+end).join(",")+"] are allowed!")
            }
        }

        this.semver = prepareSemver(currentProject.version, gitDetails.commitId, gitDetails.tags, branchName, runNumber, now)
        println("The effective version of the application is '$semver'.")

        def nowStr = now.toString() // UTC build time example: 2023-10-15T21:19:24.095308270Z
        // replace tokens @build.version@, @build.semver@ and @build.timestamp@
        if (processJavaResources) {
            currentProject.processResources {
                filesMatching(['**/*.properties', '**/*.yaml']) {
                    filter(ReplaceTokens, tokens: [
                            'build.version'  : currentProject.version,
                            'build.semver'   : this.semver,
                            'build.timestamp': nowStr 
                    ])
                }
            }
        }
    }

    /**
     * Create semver2 compatible string X.Y.Z[.R][-name]+[GIT_SHA-]yyMMddHHmm
     *
     * @param ver version of project (contains X.Y.0-*)
     * @param tags tags in formats: sha-xxxxx, X.Y.Z-*, [v[.]]X.Y.Z-*
     * @param branch an effective branch name (release/Nuuk, feature/CPD-NNNN-*, feature/CPD-NNNN-yyMMddHHmm)
     * @param runNumber CI run number
     * @return not null string
     */
    private static String prepareSemver(String ver, String sha, List<String> tags, String branch, String runNumber,
                                        OffsetDateTime now) {
        // find X.Y.Z part from several sources
        tags = tags ?: []
        def cases = tags + [branch, ver]
        def pattern = ~/^(v|v\.)?(\d+(\.\d+){2})($|[-_.].+$)/
        def result = cases.stream().filter(s -> s != null)
                .map(pattern::matcher).filter(Matcher::find).map(m -> m.group(2)).findFirst()
                .orElseThrow(() -> new GradleException("Cannot determine the app version! You need set project version or add GIT tag in format 'X.Y.Z'."))

        // adding run number as 4th part
        if (runNumber?.isNumber()) {
            result += '.' + runNumber
        }

        // find name part from several sources
        def pattern1 = ~/((v|v\.)?(\d+(\.\d+){2,3}))/
        def pattern2 = ~/^[-\s]*(.+)[-\s]*$/
        def names = [branch] + tags
        def name = names.stream().map(s -> extractName(s,pattern1, pattern2))
                .filter(s -> s != null && s.length() > 3).findFirst().orElse('')
        if (!name.isEmpty()) {
            result += '-' + name;
        }

        // add build-part
        def buildTime = DateTimeFormatter.ofPattern('yyMMddHHmm').format(now)
        result += '+' + (sha == null ? '' : sha.substring(0, 7) + '-') + buildTime
        return result.toLowerCase()
    }

    private static String extractName(String branchOrTagName, Pattern pattern1, Pattern pattern2) {
        if (branchOrTagName == null || branchOrTagName.isBlank()) {
            return null
        }
        def last = branchOrTagName.lastIndexOf('/')
        def s = branchOrTagName.substring(last + 1)
        s = pattern1.matcher(s).replaceAll('')
        def matcher = pattern2.matcher(s)
        if (!matcher.find()) {
            return null;
        }
        return matcher.group(1)
    }

}

project.extensions.create("useJavaFeatures", UseJavaFeaturesExtension)

