/**
 * Copyright (c) 2023. Cellpoint Digital
 * www.cellpointdigital.com
 *
 */

apply plugin: 'maven-publish'

java {
    withJavadocJar()
    withSourcesJar()
}

publishing {

    // destination repositories
    repositories {
        mavenLocal() // to create 'publish___PublicationToMavenLocalRepository' tasks

        maven {
            // Creates 'publish___PublicationToGHCPDRepository' task to publish artifacts into
            //   `cellpointdigital/com.cellpointdigital` repository.
            // This task is mentioned as an example, most likely you need to configure publishing at your own discretion.
            name = 'GHCPD'
            url = "https://maven.pkg.github.com/cellpointdigital/com.cellpointdigital"
            credentials {
                username = System.getenv("GITHUB_USERNAME")
                password = System.getenv("PACKAGE_REGISTRY_WRITE_TOKEN")
            }
        }

    }

}
